name: Check

on: [push, pull_request]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check coveralls --stacktrace
