name: Gradle RC Watchdog

on:
  schedule:
    - cron:  '0 0 13 * *'

jobs:
  check:
    name: Check against the Latest Gradle RC
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: rc
      - name: Check
        run: ./gradlew check coveralls
