name: Release

on:
  release:
    types: [ published ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode PGP
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secret.pgp'
          encodedString: ${{ secrets.SIGNING_SECRET_KEY_BASE64 }}
      - uses: eskatos/gradle-command-action@v1
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        with:
          arguments: gitPublishPush publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ github.ref_name }} -Prelease=true -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }} --stacktrace
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [ release ]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
          - agorapulse/agorapulse-oss
    steps:
      - uses: actions/checkout@v4
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse.testing", "module": "testing-libraries", "version": "${{ github.ref_name }}", "property" : "testing.libraries.version", "github" : ${{ toJson(github) }} }'
