name: Release

on:
  release:
    types: [ published ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Decode PGP
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secret.pgp'
          encodedString: ${{ secrets.SIGNING_SECRET_KEY_BASE64 }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        run: ./gradlew gitPublishPush publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.tag }} -Prelease=true -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [ release ]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
          - agorapulse/agorapulse-oss
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse.testing", "module": "testing-libraries", "version": "${{ steps.version.outputs.tag }}", "property" : "testing.libraries.version", "github" : ${{ toJson(github) }} }'
